- name: ignore error playbook
  hosts: all
  tasks:
    - name: shell script for error
      shell: ps-elf | grep java | grep -v grep
      ignore_errors: yes    

    - name: print hello world
      debug:
        msg: 'hello world'