- name: install java
  yum:
    state: latest
    name: java
    
- name: download tomcat 8
  get_url: "{{ TOMCAT_URL }}"
  dest: /opt/

- name: extract tomcat to opt
  unarchive: 
    src: /opt/{{ TOMCAT_ZIP }}
    dest: /opt/

- name: start service
  shell: /opt/{{TOMCAT_NAME}}/bin/catalina.sh start